name       : proj
version    : 6.3.1
release    : 4
source     :
    - https://github.com/OSGeo/PROJ/releases/download/6.3.1/proj-6.3.1.tar.gz : 6de0112778438dcae30fcc6942dee472ce31399b9e5a2b67e8642529868c86f8
license    : MIT
component  : programming.library
summary    : PROJ - Cartographic Projections and Coordinate Transformations Library. (Previously known as proj.4)
description: |
    PROJ is a generic coordinate transformation software, that transforms coordinates from one coordinate reference system (CRS) to another. This includes cartographic projections as well as geodetic transformations.
builddeps  :
    - pkgconfig(sqlite3)
replaces   :
    - proj.4
    - devel : proj.4-devel
    - dbginfo : proj.4-dbginfo
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
