name       : proj
version    : 6.2.0
release    : 3
source     :
    - https://github.com/OSGeo/PROJ/releases/download/6.2.0/proj-6.2.0.tar.gz : b300c0f872f632ad7f8eb60725edbf14f0f8f52db740a3ab23e7b94f1cd22a50
license    : MIT
component  : programming.library
summary    : PROJ - Cartographic Projections and Coordinate Transformations Library. (Previously known as proj.4)
description: |
    PROJ is a generic coordinate transformation software, that transforms coordinates from one coordinate reference system (CRS) to another. This includes cartographic projections as well as geodetic transformations.
builddeps  :
    - pkgconfig(sqlite3)
replaces   :
    - proj.4
    - devel : proj.4-devel
    - dbginfo : proj.4-dbginfo
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
