name       : proj
version    : 8.1.0
release    : 5
source     :
    - https://github.com/OSGeo/PROJ/releases/download/8.1.0/proj-8.1.0.tar.gz : 22c5cdc5aa0832077b16c95ebeec748a0942811c1c3438c33d43c8d2ead59f48
license    : MIT
component  : programming.library
summary    : PROJ - Cartographic Projections and Coordinate Transformations Library. (Previously known as proj.4)
description: |
    PROJ is a generic coordinate transformation software, that transforms coordinates from one coordinate reference system (CRS) to another. This includes cartographic projections as well as geodetic transformations.
builddeps  :
    - pkgconfig(libcurl)
    - pkgconfig(libtiff-4)
    - pkgconfig(sqlite3)
    - gtest-devel
replaces   :
    - proj.4
    - devel : proj.4-devel
    - dbginfo : proj.4-dbginfo
setup      : |
    %cmake_ninja -DUSE_EXTERNAL_GTEST=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
    rm -fr $installdir/usr/share/doc/
check      : |
    %ninja_check || :
