name       : proj.4
version    : 4.9.3
release    : 2
source     :
    - https://github.com/OSGeo/proj.4/archive/4.9.3.tar.gz : c34254f9d54e1f1fcafd322e529a6ca2785785ff99b529dc40b2a25a8a46c871
license    : MIT
component  : programming
summary    : PROJ.4 - Cartographic Projections Library
description: |
    PROJ.4 - Cartographic Projections Library
setup      : |
    %autogen --disable-static
build      : |
    %make
install    : |
    %make_install
